export { Deck } from './components/Deck'
export { STAGE_HEIGHT, STAGE_WIDTH } from './components/Stage'
export { useSlideStore } from './store/slide-store'
export * from './ui'
export type { Section, SectionId, SlideRenderContext, SlideSpec, ThreeSceneName } from './types/slide'
